# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 807a188be67348b3d23afc18e40e915868ede622697a775decdf6c06cff3235250d50fd78f951246c0942f7ddd1eafe9930635883aa7af69d57e5de4a43ef808

test:
  secret_key_base: 7583ddf8442547747ee7d162e99c8e3b3ce922e8cff944f9fb8853e680a359c5216cfcb47509185cf6c59e8e3e8f5e6179d271dcfa28d7925c5606cffa33cf54

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
